### ISSUE TITLE
Doesn't Load

### ISSUE THREAD

**Issue by Sky-rym** [OT-Archmage/SteamDeckCustomisations#1]
self explanatory

**Comment by OT-Archmage** [comment]
Which pack are you having trouble loading?

Have you tried downloading them from the plugin's theme pack store?

Have you tried reloading the plugins / restarting the deck?

Are you trying to run this alongside any other themes?

**Comment by Sky-rym** [comment]
my fault shoulda clarified
the wii theme doesn't load
loaded by itself multiple times
ive tried reloading, restarting, uninstalling
doesn't work

**Comment by OT-Archmage** [comment]
That's weird, I'm not getting any issues on my deck when downloading it from the theme store. As long as the "Wii Theme" folder is in your "homebrew/themes" folder and all the files are the same it should work.

What happens when you enable the theme? Is there an error message or crash, or does nothing happen?

Are you able to load other themes that use images? Try the "Phantom" and "Static Background" themes.

The only thing I can think of is that your CSS loader plugin might be out of date? Try reinstalling the plugin and see if that helps.

**Comment by Sky-rym** [comment]
nothing happens when i load it, and the phantom one did work
tried reinstalling and it didnt work
checked in the homebrew folder and all the stuff is there so yeah

**Comment by OT-Archmage** [comment]
I've been talking to SuchMeme (the creator of the CSS plugin) and while we still haven't figured it out yet, it looks like a dependency issue. I've pushed an update that might fix this, could you try installing this version manually and letting me know if it works?

**Comment by OT-Archmage** [comment]
Last update - it's definitely an issue with the CSS Loader Plugin, should be fixed by the next update
